AWSTemplateFormatVersion: '2010-09-09'
Description: Main template to include all other templates

Resources:
  IAMRolesStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://cloudformation-templates-shared.s3.ap-south-1.amazonaws.com/iam-roles.yml

  MFAStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://cloudformation-templates-shared.s3.ap-south-1.amazonaws.com/mfa.yml
